'use strict';

export const AUTHORIZE_SERVICE = 'AUTHORIZE_SERVICE';
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_FAILED = 'AUTHORIZE_FAILED';

export const RECEIVE_WEEKLY_STEPS = 'RECEIVE_WEEKLY_STEPS';
export const RECEIVE_TODAY_STEPS= 'RECEIVE_TODAY_STEPS';
export const RECEIVE_UPDATED_GOALS = 'RECEIVE_UPDATED_GOALS';

export const SELECT_DAY = 'SELECT_DAY';